apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: site-operator
  template:
    metadata:
      labels:
        app: site-operator
    spec:
      serviceAccountName: site-operator
      containers:
        - name: site-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.defaults.mariadbRef.name .Values.defaults.storageClassName }}
          args:
            {{- if .Values.defaults.mariadbRef.name }}
            - --default-mariadb-name={{ .Values.defaults.mariadbRef.name }}
            - --default-mariadb-namespace={{ .Values.defaults.mariadbRef.namespace }}
            {{- end }}
            {{- if .Values.defaults.storageClassName }}
            - --default-storage-class-name={{ .Values.defaults.storageClassName }}
            {{- end }}
          {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}

